config/routes.rb
Vinster::Application.routes.draw do

   root 'static_pages#index'
   resources :posts

end

app/models/post.rb
class Post < ActiveRecord::Base
	mount_uploader :image, ImageUploader

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	def index
		#everything here will be run when someone goes to /posts
		@posts = Post.all
	end

	def new
		@post = Post.new
	end

	def create
		Post.create( post_params )

		redirect_to posts_path

		# HERE
	end

	private

	def post_params
		params.require(:post).permit(:title, :description, :image)
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

	def index
		@body_class = "static_pages"
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Vinster</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body class="<%= params[:controller] %>">

<nav class="navbar navbar-inverse navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Vinster</a>
      <%= link_to 'Vinster', root_path, :class => 'navbar-brand' %>

    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        
        <li>
        <%= link_to 'My App', posts_path %>
    	</li>
    	<li>
        <%= link_to 'Add Image', new_post_path %>
    	</li>


      </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>



<%= yield %>

</body>
</html>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
	<div class="genie-box text-center col-xs-10 col-xs-offset-1 col-sm-4 col-sm-offset-1">
		<h1>
		<%= post.title%>
		</h1>

		<%= image_tag post.image, :class => 'img-responsive' %>

		<%= post.description %>

	</div>
<% end %>

app/views/posts/new.html.erb
<div class="genie-box col-xs-6 col-xs-offset-3">

<h2>
	Upload your funny image
</h2>

<br/>
<br/>

<%= simple_form_for @post do |f| %>
<%= f.input :title, label: 'What is this image about?' , placeholder: 'Drunken Monkey' %>
<br/>
<%= f.input :description, label: 'tell me more' , placeholder: 'This monkey caught a wiff and falls out of a tree'%>
<br/>
<%= f.input :image %>
<br/>

<%= f.button :submit, class: 'btn btn-warning' %>
<br/>



<% end %>

</div>

app/views/static_pages/index.html.erb
<div class="col-xs-8 col-xs-offset-2 see-box text-center" >

<h1 class="custom-h1">
	Check out my App
</h1>

<%= link_to 'launch', posts_path, :class => 'btn btn-warning'  %>

</div>